import Providers from "./providers";

import {
  Geist,
  Geist_Mono,
  Poppins,
  DM_Serif_Display,
  Rubik,
  Reem_Kufi,
} from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
Footer;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500"],
});
const dmSerifText = DM_Serif_Display({
  variable: "--font-dmSerifText",
  subsets: ["latin"],
  weight: ["400"],
});
const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ["400", "500"],
});
const reemkufi = Reem_Kufi({
  variable: "--font-reemkufi",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${dmSerifText.variable} ${rubik.variable} ${reemkufi.variable} antialiased `}
      >
        <Providers>
          <main className="bg-white min-h-100vh ">
            <Navbar />
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  );
}
